jdk:
- openjdk8
stages:
  - name: release
    if: tag IS present
before_install:
  - if [ "$TRAVIS_BUILD_STAGE_NAME" = 'Release'  ]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4;
      export PATH=$HOME/.yarn/bin:$PATH;
    fi
jobs:
  include:
    - stage: release
      script: ./sbt docs/docusaurusPublishGhpages

cache:
  directories:
    - "$HOME/.sbt"
    - "$HOME/.ivy2/cache"
    - "$HOME/.coursier"
    - "$HOME/.cache"
  yarn: true

before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.ivy2/cache -name "*scalafix*.xml" -type f -delete
- rm -rf $HOME/.ivy2/local
