import sbt._
import sbt.Keys._
import sbt.internal.ProjectMatrix
import sbtprojectmatrix.ProjectMatrixPlugin.autoImport._
import VirtualAxis.ScalaVersionAxis

/**
 * Use on ProjectMatrix rows to tag an affinity to a project with a custom
 * scalaVersion, with or without `-Xsource:3`
 */
case class TargetAxis(scalaVersion: String, xsource3: Boolean = false)
    extends VirtualAxis.WeakAxis {

  private val maybeSource3 = if (xsource3) "xsource3" else ""

  override val idSuffix =
    s"Target${scalaVersion.replace('.', '_')}$maybeSource3"
  override val directorySuffix = s"target$scalaVersion$maybeSource3"
  override val suffixOrder = VirtualAxis.scalaABIVersion("any").suffixOrder + 1
}

/** Use on ProjectMatrix rows to mark usage of "-Xsource:3" */
case object Xsource3Axis extends VirtualAxis.WeakAxis {
  override val idSuffix = "xsource3"
  override val directorySuffix = idSuffix
  override val suffixOrder = VirtualAxis.scalaABIVersion("any").suffixOrder + 2
}

case class FullScalaVersionAxis(scalaVersion: String)
    extends VirtualAxis.WeakAxis {
  override val idSuffix = scalaVersion.replace('.', '_')
  override val directorySuffix = scalaVersion
  override val suffixOrder = VirtualAxis.scalaABIVersion("any").suffixOrder + 1

  // use only the binary scala version field for equality
  override def equals(obj: Any): Boolean = {
    if (obj.isInstanceOf[AnyRef] && (this eq obj.asInstanceOf[AnyRef])) true
    else if (!obj.isInstanceOf[FullScalaVersionAxis]) false
    else {
      val o = obj.asInstanceOf[FullScalaVersionAxis]
      CrossVersion.binaryScalaVersion(this.scalaVersion) ==
        CrossVersion.binaryScalaVersion(o.scalaVersion)
    }
  }
  override def hashCode: Int = {
    37 * (17 + "sbt.FullScalaVersionAxis".hashCode()) +
      CrossVersion.binaryScalaVersion(scalaVersion).hashCode()
  }
}

object TargetAxis {

  /**
   * When invoked on a ProjectMatrix with a TargetAxis, lookup the project
   * generated by `matrix` with axes matching the TargetAxis, and resolve `key`.
   */
  def resolve[T](
      matrix: ProjectMatrix,
      key: TaskKey[T]
  ): Def.Initialize[Task[T]] =
    Def.taskDyn {
      val project = lookup(matrix, virtualAxes.value)
      Def.task((project / key).value)
    }

  /**
   * When invoked on a ProjectMatrix with a TargetAxis, lookup the project
   * generated by `matrix` with axes matching the TargetAxis, and resolve `key`.
   */
  def resolve[T](
      matrix: ProjectMatrix,
      key: SettingKey[T]
  ): Def.Initialize[T] =
    Def.settingDyn {
      val project = lookup(matrix, virtualAxes.value)
      Def.setting((project / key).value)
    }

  /**
   * Find a project in the provided matrix, matching the scalaVersion in the
   * target axis (favoring full version when available). If the target axis
   * requests `-Xsource:3` and a project tagged with Xsource3Axis exists, favor
   * this one.
   */
  private def lookup(
      matrix: ProjectMatrix,
      axisValues: Seq[VirtualAxis]
  ): Project = {

    val projects: Seq[(Project, FullScalaVersionAxis, Boolean)] =
      matrix
        .allProjects()
        .map { case (p, xs) =>
          (
            p,
            xs.collectFirst { case a: FullScalaVersionAxis => a }.get,
            xs.collectFirst { case a @ Xsource3Axis => a }.isDefined
          )
        }

    val TargetAxis(fullScalaVersion, xsource3) =
      axisValues.collectFirst { case a: TargetAxis => a }.get
    val binaryScalaVersion =
      CrossVersion.binaryScalaVersion(fullScalaVersion)

    val exactMatch = projects.collectFirst {
      case (p, FullScalaVersionAxis(sv), maybeXsource3)
          if sv == fullScalaVersion && maybeXsource3 == xsource3 =>
        p
    }
    val binaryMatch = projects.collectFirst {
      case (p, FullScalaVersionAxis(sv), _)
          if CrossVersion.binaryScalaVersion(sv) == binaryScalaVersion =>
        p
    }

    exactMatch.orElse(binaryMatch).get
  }

  implicit class TargetProjectMatrix(projectMatrix: ProjectMatrix) {

    /** Like jvmPlatform but with the full scala version attached */
    def jvmPlatformFull(
        scalaVersions: Seq[String],
        axisValues: Seq[VirtualAxis] = Nil,
        settings: Seq[Setting[_]] = Nil
    ): ProjectMatrix = {
      scalaVersions.foldLeft(projectMatrix) { (acc, full) =>
        acc.customRow(
          autoScalaLibrary = true,
          axisValues =
            axisValues :+ FullScalaVersionAxis(full) :+ VirtualAxis.jvm,
          process = {
            _.settings(
              settings ++ Seq(
                scalaVersion := full,
                // Undo what sbt-projectmatrix does in the absence of ScalaVersionAxis
                autoScalaLibrary := true,
                crossPaths := true
              )
            )
          }
        )
      }
    }

    /**
     * Like jvmPlatform but adding a separate target axis for each scala version
     */
    def jvmPlatformAgainstTargets(
        scalaVersionAgainstTarget: Seq[(String, TargetAxis)]
    ): ProjectMatrix = {
      scalaVersionAgainstTarget.foldLeft(projectMatrix) {
        case (acc, (scalaVersion, targetAxis)) =>
          acc.jvmPlatform(
            scalaVersions = Seq(scalaVersion),
            axisValues = Seq(targetAxis),
            settings = Seq()
          )
      }
    }

  }

}
